// File generated by hand to host Firebase web config. The values below are
// PLACEHOLDERS — replace them with the values from Firebase Console
// -> Project Settings -> Your apps -> Web app config.
//
// You can also let `flutterfire configure` overwrite this file when you wire
// up native platforms (iOS/Android), but for web-only the manual approach is
// simpler.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Returns true once real Firebase config is in place. While placeholders are
/// still here we skip Firebase init and let auth-gated UI render a friendly
/// "configure Firebase" hint instead of crashing.
bool get firebaseConfigured =>
    DefaultFirebaseOptions.web.apiKey != _placeholderApiKey;

const _placeholderApiKey = 'REPLACE_ME_API_KEY';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    // Native (iOS/Android) configs live in the platform-specific files
    // generated by `flutterfire configure` (GoogleService-Info.plist /
    // google-services.json). For now we return the web config so the app
    // at least boots in dev; real native shipping requires `flutterfire
    // configure` to be run.
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _placeholderApiKey,
    authDomain: 'REPLACE_ME.firebaseapp.com',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    messagingSenderId: '0',
    appId: '1:0:web:REPLACE_ME',
  );
}
